repos:
  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-added-large-files
        args: ['--maxkb=1000']
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]

  # Security: Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        stages: [pre-commit]

  # Commit message validation (Conventional Commits)
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --strict        # Enforce strict formatting (no fixup!/merge commits)
          - --force-scope   # Require scope (e.g., multilayer, server, msgs)
          # Allowed commit types
          - feat      # New feature
          - fix       # Bug fix
          - docs      # Documentation
          - style     # Formatting
          - refactor  # Code restructuring
          - perf      # Performance
          - test      # Tests
          - build     # Build system
          - ci        # CI/CD
          - chore     # Maintenance
